name: test ubuntu
on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        unity-version:
          - 2018.4.1f1
          - 2019.4.1f1
          - 2020.3.1f1
          - 2021.2.1f1
          - 2022.1.0b3
        unity-module:
          - android
          - ios
          - webgl
          - linux-il2cpp
          - mac-mono
          - windows-mono
        exclude:
          - unity-version: 2018.4.1f1
            unity-module: linux-il2cpp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check free space
        run: df -h
      - name: Setup unity
        id: setup-unity
        uses: ./
        timeout-minutes: 60
        with:
          unity-version: ${{ matrix.unity-version }}
          unity-modules: ${{ matrix.unity-module }}
      - name: Check free space
        run: df -h
      - name: Print output
        run: |
          echo unity-version: ${{ steps.setup-unity.outputs.unity-version }}
          echo unity-path: ${{ steps.setup-unity.outputs.unity-path }}
          echo env UNITY_PATH: ${{ env.UNITY_PATH }}
